title: Armando Vasquez
description: Data Science Portfolio
url: "https://armandohvasquez.github.io"

theme: minima

header_pages:
  - about.md
  - projects.md
  - resume.md

collections:
  projects:
    output: true
    permalink: /projects/:name/

plugins:
  - jekyll-feed
